language: php
dist: trusty
php:
  - 7
  - 7.1
  - 7.2

services:
  - mysql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

script:
  - ./vendor/bin/phpunit --coverage-clover 'reports/clover.xml'

before_script:
  #MySQL database init
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -uroot -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)
